version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: openspace_db
    restart: unless-stopped
    ports:
      - "2010:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - db_data_openspace:/var/lib/postgresql/data

volumes:
  db_data_openspace: